baseURL = 'http://nancyjlau.github.io/'
languageCode = 'en-us'
title = 'root@catgirl ~ $'
theme = 'archie'
copyright = "© rose"
favicon = "https://cdn.discordapp.com/attachments/803939510374236210/1133225874792128626/image.png"
description = "hi"
disableKinds = ["RSS"]

[params]
	mode="toggle"
	description = "bits about malware development, hardware, and cybersecurity"
	subtitle = "bits about maldev, hardware, and cybersec"
	mathjax = true 
	katex = true 

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nancyjlau"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nachoyawn/"

# Main menu Items

[[menu.main]]
name = "~/home"
url = "/"
weight = 1

[[menu.main]]
name = "~/about"
url = "/about"
weight = 2

[[menu.main]]
name = "~/posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "~/tags"
url = "/tags"
weight = 4